
dataset: Kitti
split: eigen_zhou

# DataLoading
batch_size: 6
image_size: [192, 640]

# Model
depthmodel: MonoDepth2 # or Dorn
backbone: resnet18
context: Null # one of [Null, aspp, psp]
pyramid: Null
regression: True

# Training
max_epochs: 20
crop_size: Null
