
dataset: Kitti
split: eigen_zhou

# DataLoading
batch_size: 12
image_size: [128, 416]

# Model
depthmodel: Dorn
backbone: resnet18
context: aspp # one of [Null, aspp, psp]
pyramid: [6, 12, 18] # TODO ?
regression: True

# Training
max_epochs: 20
crop_size: Null
