
dataset: Kitti
split: eigen_zhou

# DataLoading
batch_size: 12
image_size: [128, 416]

# Model
depthmodel: Dorn
backbone: resnet18
context: ASPP # one of [Null, Dorn, ASPP, PSP]
pyramid: [2, 6] # [2, 4, 8]
regression: False

# Training
max_epochs: 20
crop_size: Null
